### ISSUE TITLE
Deleting removed extractors

### ISSUE THREAD

**Issue by Darius-Hutchison** [DavidEdwards/EVE-PI#13]
I created an extractor and then removed it later. The tracker still listed the extractor as on be has ran out.

**Comment by DavidEdwards** [comment]
Alright, I was hoping my previous versions fixed that. I will need to look at this again.

**Comment by DavidEdwards** [comment]
When I test this on my version, it works. I will upload the latest version, lets see whether that fixes it for you.

**Comment by Darius-Hutchison** [comment]
Checked out the new version and they are still there.

**Comment by DavidEdwards** [comment]
I cannot replicate this issue. I have tried deleting extractors. Refreshing. First refresh, they usually stay on the display due to caching. Second refresh, they are gone.

Have you tried manually refreshing? On the extractors page, drag your finger down to force a refresh from the ESI servers.

If you still have this issue, uninstall the App then install it again. If that doesn't work, there isn't much that I can do without a test case to work with. I will close this issue for now.
