### ISSUE TITLE
Factory planet watcher

### ISSUE THREAD

**Issue by kordusj** [DavidEdwards/EVE-PI#27]
Not a bug: app took me here to suggest a feature.
It would be cool to be able to see if factories are running or not. Contents isnt that important but at least being able to know if they are running or not would be nice.

**Comment by DavidEdwards** [comment]
Yep, you can add requests here too!

I'll have a look at the API. This seems like a good idea.

**Comment by DavidEdwards** [comment]
So. Some more investigation into this yields negative results.

Due to the way the caching works for PI this will not be achievable. 

The numbers are only refreshed when you visit a planet. This is fine for monitoring extractors because you need to personally turn the extractors back on again in order for them to work. That means visiting the planet (and refreshing the numbers).

In contrast, factories will continue to cycle regardless of what you are doing. That means that you cannot know whether your factories are currently operating or not. It will mark the time of the last cycle as the cycle from the last time you refreshed the planet data by visiting it. 

I will set this issue as blocked by ESI and not close it. I would very much like to build this feature in the future.

**Comment by kordusj** [comment]
Interesting. There was an old app on ios called neocom that had monitoring
of factory planets in that i think it would show the volume of product and
it had a data base of input volume to output volume so i think it could
roughly calculate exipry time. Im not sure if the api changed since last
year though. May be a different angle to approach it from. I dont know much
about api stuff unfortunatly.

**Comment by DavidEdwards** [comment]
Thanks to the work of tsuthers-ccpgames (and presumably others). Work has now begun on implementing changes that will bring storage and factories all together.

**Comment by DavidEdwards** [comment]
Condensing this issue into #40
