### ISSUE TITLE
Show the status of the launch pad and more details for a planet

### ISSUE THREAD

**Issue by ckroehnert** [DavidEdwards/EVE-PI#37]
It would be great if you could show the status of the launch pad and if it reach the fill limit while the current circle.

I will add later an image how it is realized in neocom.

**Comment by ckroehnert** [comment]
https://drive.google.com/file/d/0B2wKzkI8KwqqNXRydmJfQmVTQ0U/view?usp=drivesdk

**Comment by DavidEdwards** [comment]
That's smart. Though it does use the XML API in order to get the actual current contents of the storage. I have been wanting to stick to the ESI API where possible. However, it looks like this isn't getting support anytime soon in ESI :-(

https://github.com/ccpgames/esi-issues/issues/161

I'll have a look at this soon-ish.

**Comment by ckroehnert** [comment]
It is just an idea. If it is not possible it is also okay. If you add the feature I will pay 100mio ISK (as incentive ;-) )

**Comment by BBrey** [comment]
It is possible to calculate the amount of product in the launchpad since you reset the extractors but that's it for now.

**Comment by ghost** [comment]
Hey all, the supporting changes for this in ESI have happened and will release any day now. Updates here:

https://github.com/ccpgames/esi-issues/issues/161

**Comment by DavidEdwards** [comment]
Thanks @tsuthers-ccpgames. Work has now begun on implementing changes that will bring storage and factories all together.

**Comment by DavidEdwards** [comment]
Condensing this issue into #40
