### ISSUE TITLE
Request:  Storage full detection

### ISSUE THREAD

**Issue by ryanrenn** [DavidEdwards/EVE-PI#41]
I've uses another app on an apple device that has an awesome pi monitoring feature.     It tells you when your storage or launched will be full... of if it's overflowing and you're losing materials.

**Comment by DavidEdwards** [comment]
That is a part of this issue: https://github.com/DavidEdwards/EVE-PI/issues/40

I am in the process of building a simulator system that will run PI as close as possible to how EVE runs PI.

In this way, it will provide warnings about all aspects of PI by knowing exactly when things will need to be checked.

So I will close this issue, since it is more-or-less the same thing as #40.
