### ISSUE TITLE
Shedul notification (off notification in Nights)

### ISSUE THREAD

**Issue by PolyG0ne** [DavidEdwards/EVE-PI#48]
Notification disable between X ans Y hour :D 

Thanks !

**Comment by RobertMathieu** [comment]
You can use the "do not disturb" functionality of your smartphone to do this. You can give hours for automatic activation and even set some app that can by pass the do not disturb.

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time.

Yep, do not disturb is a great feature.

Since I use Google services to run my jobs, it is more difficult to get them to run at specific times. But for this reason you get improved battery life. So it has its upsides!
